#!/usr/bin/env bash

set -e

echo "==> Updating Homebrew..."
brew update

brew bundle check >/dev/null 2>&1 || {
  echo "==> Installing Homebrew dependencies..."
  brew bundle
}

echo "==> Starting PostgreSQL service..."
brew services restart postgres

echo "==> Installing Node dependencies..."
nodenv install `cat .node-version`
npm install

echo "Creating database"
createdb barebones || true

echo "Running migrations"
npm run migrate

echo "Seeding DB"
node script/seeddb.js

echo "Ready to rock, run ['npm run dev'] to get coding"
