#!/usr/bin/env bash

set -e

echo "==> Updating Homebrew..."
brew update

brew bundle check >/dev/null 2>&1 || {
  echo "==> Installing Homebrew dependencies..."
  brew bundle
}

echo "==> Starting PostgreSQL service..."
brew services restart postgres

echo "==> Installing Node dependencies..."
npm install

echo "Creating database"
createdb barebones || true

echo "Running migrations"
npm run migrate

echo "Ready to rock, run [npm run dev] to get coding"
